CREATE TABLE DEPARTEMEN(
NO_DEPT CHAR(15) NOT NULL,
NAMA_DEPT CHAR(35) NOT NULL,
PRIMARY KEY (NO_DEPT));

CREATE TABLE PEGAWAI(
NO_PEG CHAR(6) PRIMARY KEY NOT NULL,
NAMA_PEGAWAI CHAR(40) NOT NULL,
NO_HP CHAR(15) NOT NULL,
NO_DEPT CHAR(15) NOT NULL,
FOREIGN KEY (NO_DEPT) REFERENCES DEPARTEMEN (NO_DEPT)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE PEGAWAI(
NO_PEG CHAR(5) PRIMARY KEY NOT NULL,
NAMA_PEGAWAI CHAR(40) NOT NULL,
NO_HP CHAR(15) NOT NULL,
NO_PEMIMPIN CHAR(5),
FOREIGN KEY (NO_PEMIMPIN) REFERENCES PEGAWAI(NO_PEG)
ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE DEPT_PEG(
NO_DEPT CHAR(15),
NO_PEG CHAR(5),
NAMA_DEPT CHAR(35) NOT NULL,
FOREIGN KEY (NO_DEPT) REFERENCES DEPARTEMEN (NO_DEPT),
FOREIGN KEY (NO_PEG) REFERENCES PEGAWAI(NO_PEG)
ON DELETE RESTRICT ON UPDATE CASCADE);


-- Latihan 1
-- Create DOSEN table
CREATE TABLE DOSEN (
    ID_DOSEN VARCHAR(10) PRIMARY KEY,
    NAMA_DOSEN VARCHAR(100) NOT NULL,
    EMAIL_DOSEN VARCHAR(100) UNIQUE
);

-- Create KULIAH table
CREATE TABLE KULIAH (
    ID_KULIAH VARCHAR(10) PRIMARY KEY,
    NAMA_KULIAH VARCHAR(100) NOT NULL,
    SKS INT NOT NULL,
    ID_DOSEN VARCHAR(10),
    FOREIGN KEY (ID_DOSEN) REFERENCES DOSEN(ID_DOSEN)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- Sample data for LATIHAN 1
INSERT INTO DOSEN (ID_DOSEN, NAMA_DOSEN, EMAIL_DOSEN) VALUES
('D001', 'Dr. Ahmad Santoso', 'ahmad.santoso@university.ac.id'),
('D002', 'Prof. Siti Rahayu', 'siti.rahayu@university.ac.id'),
('D003', 'Dr. Budi Prakoso', 'budi.prakoso@university.ac.id');

INSERT INTO KULIAH (ID_KULIAH, NAMA_KULIAH, SKS, ID_DOSEN) VALUES
('K001', 'Basis Data', 3, 'D001'),
('K002', 'Pemrograman Web', 4, 'D001'),
('K003', 'Struktur Data', 3, 'D002'),
('K004', 'Algoritma', 4, 'D002'),
('K005', 'Jaringan Komputer', 3, 'D003');

-- Latihan 2
-- Create DOSEN table with composite attribute
CREATE TABLE DOSEN_V2 (
    ID_DOSEN VARCHAR(10) PRIMARY KEY,
    NAMA_DEPAN_DOSEN VARCHAR(50) NOT NULL,
    NAMA_BELAKANG_DOSEN VARCHAR(50) NOT NULL,
    EMAIL_DOSEN VARCHAR(100) UNIQUE
);

-- Create KULIAH table with NO_DEPT
CREATE TABLE KULIAH_V2 (
    ID_KULIAH VARCHAR(10) PRIMARY KEY,
    NAMA_KULIAH VARCHAR(100) NOT NULL,
    NO_DEPT VARCHAR(10)
);

-- Create junction/bridge table for Many-to-Many relationship
CREATE TABLE DOSEN_KULIAH (
    ID_DOSEN VARCHAR(10),
    ID_KULIAH VARCHAR(10),
    PRIMARY KEY (ID_DOSEN, ID_KULIAH),
    FOREIGN KEY (ID_DOSEN) REFERENCES DOSEN_V2(ID_DOSEN)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ID_KULIAH) REFERENCES KULIAH_V2(ID_KULIAH)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);